"""Fresh restart for Phase 5

Revision ID: 605ab153b2d1
Revises: 
Create Date: 2025-11-20 17:25:09.516043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605ab153b2d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('lecturer_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_user_id'], ['users.id'], name=op.f('fk_courses_lecturer_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('code', name=op.f('uq_courses_code'))
    )
    op.create_table('course_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_keywords', sa.String(length=255), nullable=True),
    sa.Column('topic_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_topics_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_topics'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('quality_rating', sa.Integer(), nullable=False),
    sa.Column('assignment_rating', sa.Integer(), nullable=False),
    sa.Column('grading_rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_category', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_flagged_for_review', sa.Boolean(), nullable=True),
    sa.Column('predicted_quality', sa.Float(), nullable=True),
    sa.Column('predicted_assignment', sa.Float(), nullable=True),
    sa.Column('predicted_grading', sa.Float(), nullable=True),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_feedback_course_id_courses')),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], name=op.f('fk_feedback_student_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('course_topics')
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
